version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "5c:cd:40:43:00:08:2b:65:fc:f0:39:9d:7d:25:c8:51"

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install -D

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run: npm run build

      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  publish:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: chmod +x publish.sh && ./publish.sh

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: /book/
      - publish:
          requires:
            - build
          filters:
            branches:
              only: /book/



